Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -142,7 +142,48 @@ jobs:
           echo "Using SOURCE_BRANCH: $SOURCE_BRANCH in DIY_P2_SH" 
           cd openwrt/
           ${GITHUB_WORKSPACE}/${DIY_P2_SH}
+          
+          # 根据 subtarget 构建配置字符串
+          if [[ "$SUBTARGET" == "rk33xx" ]]; then
+            target_config="
+            CONFIG_TARGET_rockchip_armv8=y
+            CONFIG_TARGET_rockchip_armv8_DEVICE_$SOURCE_BOARD=y
+            CONFIG_TARGET_SUBTARGET=\"armv8\"
+            CONFIG_TARGET_PROFILE=\"DEVICE_$SOURCE_BOARD\"
+            CONFIG_TARGET_ARCH_PACKAGES=\"aarch64_generic\"
+            CONFIG_DEFAULT_TARGET_OPTIMIZATION=\"-Os -pipe -mcpu=generic\"
+            CONFIG_CPU_TYPE=\"generic\"
+            "
+          elif [[ "$SUBTARGET" == "rk35xx" ]]; then
+            target_config="
+            CONFIG_TARGET_rockchip_rk35xx=y
+            CONFIG_TARGET_rockchip_rk35xx_DEVICE_$SOURCE_BOARD=y
+            CONFIG_TARGET_SUBTARGET=\"rk35xx\"
+            CONFIG_TARGET_PROFILE=\"DEVICE_$SOURCE_BOARD\"
+            CONFIG_TARGET_ARCH_PACKAGES=\"aarch64_cortex-a53\"
+            CONFIG_DEFAULT_TARGET_OPTIMIZATION=\"-Os -pipe -mcpu=cortex-a53\"
+            CONFIG_CPU_TYPE=\"cortex-a53\"
+            "
+          else
+            echo "Error: Unsupported rockchip_subtarget: $SUBTARGET"
+            exit 1
+          fi
+
+          # 定义一个函数来将配置添加到文件开头（如果尚未存在）
+          prepend_if_not_exists() {
+            local line="$1"
+            local file="$2"
+            # 使用 awk 来检查行是否已存在，如果不存在，则将其添加到文件开头
+            awk -v line="$line" 'BEGIN{if(!seen[line]) print line; seen[line]=1} {print}' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
+          }
+
+          # 逐行处理配置，并添加到文件开头
+          while IFS= read -r line; do
+            prepend_if_not_exists "$line" ".config"
+          done <<< "$target_config"
+
           ls -la
+          cat .config
 
       - name: Verify Configuration Items
         id: verify_config
